### ISSUE TITLE
[MOS-001] Add Journal Entry

### ISSUE THREAD

**Issue by igsellmann** [sw21-tug/Team_12#1]
**As a**
user
**I want to**
add a journal entry
**so that**
I can archive things.

**Add Field and Add Attachment does not have to be impleneted for now!!**

**Acceptance Criteria:**
- [x] Entry writing frame with title and content field
- [x] Cancel & Save buttons
- [x] Entry is saved to a database when pressing save
- [x] Entry has to appear in the Overview screen

**Comment by fdnuka** [comment]
Estimated: 5 story points
