### ISSUE TITLE
[MOS-004] Entry Overview

### ISSUE THREAD

**Issue by igsellmann** [sw21-tug/Team_12#6]
**As a**
user
**I want to**
see a list of my entries on the app homescreen
**so that**
I can sroll through them and see them all.

- [x] Create the tables that will contain the rows
- [x] Add the menu bar 'My open secrete'
- [x] Create the right menu with the 'Tag', 'Filter' and 'New Entry' buttons
- [x] Scroll bar to see the list of journals

**Comment by fdnuka** [comment]
Estimated: 3 story points
