### ISSUE TITLE
[MOS-003] Delete Entries

### ISSUE THREAD

**Issue by igsellmann** [sw21-tug/Team_12#7]
**As a**
user
**I want to**
delete entries
**so that**
I can get rid of data I no longer need.

**Acceptance Criteria:**

- [ ] Add the delete button on 'View' & 'Edit' screens
- [ ] On 'Delete' button click open the prompt that will ask for the user's approval with 'Yes' & 'No' buttons on it
- [ ] On user's approval delete the data from the database and return to the home screen

**Comment by fdnuka** [comment]
Estimated: 2 story points
